<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            [
                'name' => 'Indonesia',
                'official_name' => 'Republic of Indonesia',
                'iso2' => 'ID',
                'iso3' => 'IDN',
                'capital' => 'Jakarta',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
                'currency_code' => 'IDR',
                'currency_name' => 'Indonesian Rupiah',
                'currency_symbol' => 'Rp',
                'population' => 281603800,
                'latitude' => -6.2088000,
                'longitude' => 106.8456000,
                'timezone' => 'Asia/Jakarta',
                'flag_url' => 'https://flagcdn.com/w320/id.png',
                'is_active' => true,
                'last_synced_at' => now(),
            ],
            [
                'name' => 'China',
                'official_name' => 'People\'s Republic of China',
                'iso2' => 'CN',
                'iso3' => 'CHN',
                'capital' => 'Beijing',
                'region' => 'Asia',
                'subregion' => 'Eastern Asia',
                'currency_code' => 'CNY',
                'currency_name' => 'Chinese Yuan',
                'currency_symbol' => '¥',
                'population' => 1408280000,
                'latitude' => 39.9042000,
                'longitude' => 116.4074000,
                'timezone' => 'Asia/Shanghai',
                'flag_url' => 'https://flagcdn.com/w320/cn.png',
                'is_active' => true,
                'last_synced_at' => now(),
            ],
            [
                'name' => 'Japan',
                'official_name' => 'Japan',
                'iso2' => 'JP',
                'iso3' => 'JPN',
                'capital' => 'Tokyo',
                'region' => 'Asia',
                'subregion' => 'Eastern Asia',
                'currency_code' => 'JPY',
                'currency_name' => 'Japanese Yen',
                'currency_symbol' => '¥',
                'population' => 123975371,
                'latitude' => 35.6762000,
                'longitude' => 139.6503000,
                'timezone' => 'Asia/Tokyo',
                'flag_url' => 'https://flagcdn.com/w320/jp.png',
                'is_active' => true,
                'last_synced_at' => now(),
            ],
            [
                'name' => 'United States',
                'official_name' => 'United States of America',
                'iso2' => 'US',
                'iso3' => 'USA',
                'capital' => 'Washington, D.C.',
                'region' => 'Americas',
                'subregion' => 'Northern America',
                'currency_code' => 'USD',
                'currency_name' => 'United States Dollar',
                'currency_symbol' => '$',
                'population' => 340110988,
                'latitude' => 38.9072000,
                'longitude' => -77.0369000,
                'timezone' => 'America/New_York',
                'flag_url' => 'https://flagcdn.com/w320/us.png',
                'is_active' => true,
                'last_synced_at' => now(),
            ],
            [
                'name' => 'Germany',
                'official_name' => 'Federal Republic of Germany',
                'iso2' => 'DE',
                'iso3' => 'DEU',
                'capital' => 'Berlin',
                'region' => 'Europe',
                'subregion' => 'Western Europe',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'currency_symbol' => '€',
                'population' => 83577140,
                'latitude' => 52.5200000,
                'longitude' => 13.4050000,
                'timezone' => 'Europe/Berlin',
                'flag_url' => 'https://flagcdn.com/w320/de.png',
                'is_active' => true,
                'last_synced_at' => now(),
            ],
            [
                'name' => 'Australia',
                'official_name' => 'Commonwealth of Australia',
                'iso2' => 'AU',
                'iso3' => 'AUS',
                'capital' => 'Canberra',
                'region' => 'Oceania',
                'subregion' => 'Australia and New Zealand',
                'currency_code' => 'AUD',
                'currency_name' => 'Australian Dollar',
                'currency_symbol' => '$',
                'population' => 27204400,
                'latitude' => -35.2809000,
                'longitude' => 149.1300000,
                'timezone' => 'Australia/Sydney',
                'flag_url' => 'https://flagcdn.com/w320/au.png',
                'is_active' => true,
                'last_synced_at' => now(),
            ],
            [
                'name' => 'India',
                'official_name' => 'Republic of India',
                'iso2' => 'IN',
                'iso3' => 'IND',
                'capital' => 'New Delhi',
                'region' => 'Asia',
                'subregion' => 'Southern Asia',
                'currency_code' => 'INR',
                'currency_name' => 'Indian Rupee',
                'currency_symbol' => '₹',
                'population' => 1450935791,
                'latitude' => 28.6139000,
                'longitude' => 77.2090000,
                'timezone' => 'Asia/Kolkata',
                'flag_url' => 'https://flagcdn.com/w320/in.png',
                'is_active' => true,
                'last_synced_at' => now(),
            ],
            [
                'name' => 'Singapore',
                'official_name' => 'Republic of Singapore',
                'iso2' => 'SG',
                'iso3' => 'SGP',
                'capital' => 'Singapore',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
                'currency_code' => 'SGD',
                'currency_name' => 'Singapore Dollar',
                'currency_symbol' => '$',
                'population' => 6036860,
                'latitude' => 1.3521000,
                'longitude' => 103.8198000,
                'timezone' => 'Asia/Singapore',
                'flag_url' => 'https://flagcdn.com/w320/sg.png',
                'is_active' => true,
                'last_synced_at' => now(),
            ],
            [
                'name' => 'Malaysia',
                'official_name' => 'Malaysia',
                'iso2' => 'MY',
                'iso3' => 'MYS',
                'capital' => 'Kuala Lumpur',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
                'currency_code' => 'MYR',
                'currency_name' => 'Malaysian Ringgit',
                'currency_symbol' => 'RM',
                'population' => 35557673,
                'latitude' => 3.1390000,
                'longitude' => 101.6869000,
                'timezone' => 'Asia/Kuala_Lumpur',
                'flag_url' => 'https://flagcdn.com/w320/my.png',
                'is_active' => true,
                'last_synced_at' => now(),
            ],
            [
                'name' => 'South Korea',
                'official_name' => 'Republic of Korea',
                'iso2' => 'KR',
                'iso3' => 'KOR',
                'capital' => 'Seoul',
                'region' => 'Asia',
                'subregion' => 'Eastern Asia',
                'currency_code' => 'KRW',
                'currency_name' => 'South Korean Won',
                'currency_symbol' => '₩',
                'population' => 51751065,
                'latitude' => 37.5665000,
                'longitude' => 126.9780000,
                'timezone' => 'Asia/Seoul',
                'flag_url' => 'https://flagcdn.com/w320/kr.png',
                'is_active' => true,
                'last_synced_at' => now(),
            ],
            [
                'name' => 'United Kingdom',
                'official_name' => 'United Kingdom of Great Britain and Northern Ireland',
                'iso2' => 'GB',
                'iso3' => 'GBR',
                'capital' => 'London',
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'currency_code' => 'GBP',
                'currency_name' => 'British Pound Sterling',
                'currency_symbol' => '£',
                'population' => 67736802,
                'latitude' => 51.5074000,
                'longitude' => -0.1278000,
                'timezone' => 'Europe/London',
                'flag_url' => 'https://flagcdn.com/w320/gb.png',
                'is_active' => true,
                'last_synced_at' => now(),
            ],
            [
                'name' => 'France',
                'official_name' => 'French Republic',
                'iso2' => 'FR',
                'iso3' => 'FRA',
                'capital' => 'Paris',
                'region' => 'Europe',
                'subregion' => 'Western Europe',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'currency_symbol' => '€',
                'population' => 68070697,
                'latitude' => 48.8566000,
                'longitude' => 2.3522000,
                'timezone' => 'Europe/Paris',
                'flag_url' => 'https://flagcdn.com/w320/fr.png',
                'is_active' => true,
                'last_synced_at' => now(),
            ],
            [
                'name' => 'Canada',
                'official_name' => 'Canada',
                'iso2' => 'CA',
                'iso3' => 'CAN',
                'capital' => 'Ottawa',
                'region' => 'Americas',
                'subregion' => 'Northern America',
                'currency_code' => 'CAD',
                'currency_name' => 'Canadian Dollar',
                'currency_symbol' => '$',
                'population' => 40097761,
                'latitude' => 45.4215000,
                'longitude' => -75.6972000,
                'timezone' => 'America/Toronto',
                'flag_url' => 'https://flagcdn.com/w320/ca.png',
                'is_active' => true,
                'last_synced_at' => now(),
            ],
            [
                'name' => 'Brazil',
                'official_name' => 'Federative Republic of Brazil',
                'iso2' => 'BR',
                'iso3' => 'BRA',
                'capital' => 'Brasília',
                'region' => 'Americas',
                'subregion' => 'South America',
                'currency_code' => 'BRL',
                'currency_name' => 'Brazilian Real',
                'currency_symbol' => 'R$',
                'population' => 216422446,
                'latitude' => -15.7975000,
                'longitude' => -47.8919000,
                'timezone' => 'America/Sao_Paulo',
                'flag_url' => 'https://flagcdn.com/w320/br.png',
                'is_active' => true,
                'last_synced_at' => now(),
            ],
            [
                'name' => 'Russia',
                'official_name' => 'Russian Federation',
                'iso2' => 'RU',
                'iso3' => 'RUS',
                'capital' => 'Moscow',
                'region' => 'Europe',
                'subregion' => 'Eastern Europe',
                'currency_code' => 'RUB',
                'currency_name' => 'Russian Ruble',
                'currency_symbol' => '₽',
                'population' => 143826130,
                'latitude' => 55.7558000,
                'longitude' => 37.6173000,
                'timezone' => 'Europe/Moscow',
                'flag_url' => 'https://flagcdn.com/w320/ru.png',
                'is_active' => true,
                'last_synced_at' => now(),
            ],
            [
                'name' => 'Saudi Arabia',
                'official_name' => 'Kingdom of Saudi Arabia',
                'iso2' => 'SA',
                'iso3' => 'SAU',
                'capital' => 'Riyadh',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'currency_code' => 'SAR',
                'currency_name' => 'Saudi Riyal',
                'currency_symbol' => 'SR',
                'population' => 32175224,
                'latitude' => 24.7136000,
                'longitude' => 46.6753000,
                'timezone' => 'Asia/Riyadh',
                'flag_url' => 'https://flagcdn.com/w320/sa.png',
                'is_active' => true,
                'last_synced_at' => now(),
            ],
            [
                'name' => 'Thailand',
                'official_name' => 'Kingdom of Thailand',
                'iso2' => 'TH',
                'iso3' => 'THA',
                'capital' => 'Bangkok',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
                'currency_code' => 'THB',
                'currency_name' => 'Thai Baht',
                'currency_symbol' => '฿',
                'population' => 71801279,
                'latitude' => 13.7563000,
                'longitude' => 100.5018000,
                'timezone' => 'Asia/Bangkok',
                'flag_url' => 'https://flagcdn.com/w320/th.png',
                'is_active' => true,
                'last_synced_at' => now(),
            ],
            [
                'name' => 'Vietnam',
                'official_name' => 'Socialist Republic of Vietnam',
                'iso2' => 'VN',
                'iso3' => 'VNM',
                'capital' => 'Hanoi',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
                'currency_code' => 'VND',
                'currency_name' => 'Vietnamese Dong',
                'currency_symbol' => '₫',
                'population' => 98858950,
                'latitude' => 21.0285000,
                'longitude' => 105.8542000,
                'timezone' => 'Asia/Ho_Chi_Minh',
                'flag_url' => 'https://flagcdn.com/w320/vn.png',
                'is_active' => true,
                'last_synced_at' => now(),
            ],
            [
                'name' => 'Netherlands',
                'official_name' => 'Kingdom of the Netherlands',
                'iso2' => 'NL',
                'iso3' => 'NLD',
                'capital' => 'Amsterdam',
                'region' => 'Europe',
                'subregion' => 'Western Europe',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'currency_symbol' => '€',
                'population' => 17811291,
                'latitude' => 52.3676000,
                'longitude' => 4.9041000,
                'timezone' => 'Europe/Amsterdam',
                'flag_url' => 'https://flagcdn.com/w320/nl.png',
                'is_active' => true,
                'last_synced_at' => now(),
            ],
            [
                'name' => 'Turkey',
                'official_name' => 'Republic of Türkiye',
                'iso2' => 'TR',
                'iso3' => 'TUR',
                'capital' => 'Ankara',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'currency_code' => 'TRY',
                'currency_name' => 'Turkish Lira',
                'currency_symbol' => '₺',
                'population' => 85372377,
                'latitude' => 39.9334000,
                'longitude' => 32.8597000,
                'timezone' => 'Europe/Istanbul',
                'flag_url' => 'https://flagcdn.com/w320/tr.png',
                'is_active' => true,
                'last_synced_at' => now(),
            ],
        ];

        foreach ($countries as $country) {
            Country::updateOrCreate(
                ['iso3' => $country['iso3']],
                $country
            );
        }
    }
}